<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE arboles [
    <!ELEMENT arboles (arbol+)>
    <!ELEMENT arbol (nom?,nombre?,vegetacion?,alt?,forma?,ColorPrim?,ColorOto?,resist?)>
    <!ELEMENT nom (#PCDATA)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT vegetacion (#PCDATA)>
    <!ELEMENT alt (#PCDATA)>
    <!ELEMENT forma (#PCDATA)>
    <!ELEMENT ColorPrim (#PCDATA)>
    <!ELEMENT resist (#PCDATA)>
    <!ELEMENT ColorOto (#PCDATA)>

]>

<arboles>
    <arbol>
        <nom>Acer monspessulanum</nom>
        <nombre>Arce de Montpellier, Arce menor</nombre>
        <vegetacion>Caducifolio</vegetacion>
        <alt>De 6 a 10 metros</alt>
        <forma>Copa esférica. Tronco principal recto con bifurcaciones. Ramaje colgante</forma>
        <ColorPrim>Haz verde brillante, envés verde blanquecino</ColorPrim>
        <resist>Heladas fuertes (hasta -15ºC)</resist>
    </arbol>

    <arbol>
        <nom>Olea europea</nom>
        <nombre>Olivo</nombre>
        <vegetacion>Perenne</vegetacion>
        <alt>De 8 a 15 metros</alt>
        <forma>Copa irregular. Tronco principal irregular con bifurcaciones.</forma>
    </arbol>

    <arbol>
        <ColorPrim>Haz verde oscuro, envés verde plateado</ColorPrim>
        <resist>Heladas fuertes (hasta -10ºC)</resist>
    </arbol>

    <arbol>
        <nom>Platanus orientalis</nom>
        <nombre>Platano</nombre>
        <vegetacion>Caducifolio</vegetacion>
        <alt>De 20 a 25 metros</alt>
        <forma>Copa ovoidal. Tronco principal recto. Ramaje expandido</forma>
        <ColorPrim>Haz verde medio, enves verde claro</ColorPrim>
        <ColorOto>Ocre</ColorOto>
        <resist>Heladas fuertes (hasta -20ºC)</resist>
    </arbol>

    <arbol>
        <nom>Quercus ilex</nom>
        <nombre>Encina</nombre>
        <vegetacion>Perenne</vegetacion>
        <alt>En torno a 25 metros</alt>
        <forma>Copa esférica o elíptica irregular. Tronco principal recto. Ramaje tortuoso</forma>
        <ColorPrim> Plateado en hojas jóvenes. En hojas antiguas, haz verde oscuro, envés plateado</ColorPrim>
        <resist>Heladas fuertes (hasta -15ºC)</resist>
    </arbol>


</arboles>