<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mensaje [
    <!ELEMENT mensaje (remite,destinatario,asunto,texto)>
    <!ELEMENT remite (nombre,email)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT destinatario (nombre,email)>
    <!ELEMENT asunto (#PCDATA)>
    <!ELEMENT parrafo (#PCDATA)>
    <!ELEMENT otros (#PCDATA)>
    <!ELEMENT texto (parrafo,otros)>
   
]>
<mensaje>
<remite>
    <nombre>Alfredo Reino</nombre>
    <email>alf@ibium.com</email>
</remite>
<destinatario>
    <nombre>Bill Clinton</nombre>
    <email>presidente@whitehouse.gov</email>
</destinatario>
<asunto>Hola bill</asunto>
<texto>
    <parrafo>Â¿Hola que tal?</parrafo>
    <otros>...</otros>
</texto>


</mensaje>